import { Inter, Bebas_Neue } from "next/font/google";
import "./globals.css";



const inter = Inter({
  // variable: "--font-geist-mono",
  weight: ['400', '500' , '700', '600' , '800' , '900'],
  subsets: ["latin", 'cyrillic'],
  display: 'swap',
  style: 'normal'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
